/*
 * Copyright (c) 2004-2006 Marco Maccaferri and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Marco Maccaferri - initial API and implementation
 */

package net.sourceforge.eclipsetrader.charts;

import net.sourceforge.eclipsetrader.core.db.BarData;

/**
 * Interface that must be implemented by all indicator plugins.
 * 
 * @see IndicatorPlugin
 * @since 1.0
 */
public interface IIndicatorPlugin
{

    /**
     * Disposes of all resources allocated by the receiver.
     */
    public abstract void dispose();

    /**
     * Set the input data.
     */
    public abstract void setInput(BarData barData);

    /**
     * Return the collection of output data generated by the plugin.
     */
    public abstract Indicator getOutput();

    /**
     * Clear the output collection.
     */
    public abstract void clearOutput();

    /**
     * Calculate the output values.
     */
    public abstract void calculate();

    /**
     * Set the parameters used by the plugin to do the calculations.
     */
    public abstract void setParameters(Settings settings);
}
